Web/Controllers/ValidarDXController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.IO;
using Newtonsoft.Json;
using System.Dynamic;
using System.Text.Json;
using System.Web.Script.Serialization;
using System.Security.Policy;
using Ubiety.Dns.Core;
using Newtonsoft.Json.Linq;
using System.Data.Entity.Infrastructure;
using log4net;
using System.Data.Entity.Core.Objects;
using PuedesPasARG.Models;
using System.Web.Helpers;
using System.Data.SqlClient;
using System.Data;
using System.Text.RegularExpressions;
using Microsoft.Win32;
using Org.BouncyCastle.Bcpg.OpenPgp;
using System.Collections;

namespace PuedesPasARG.Controllers
{
    // ILog log = log4net.LogManager.GetLogger(typeof(HomeController));

    public class ValidarDXController : Controller
    {
        private static log4net.ILog Log { get; set; }
        ILog log = log4net.LogManager.GetLogger(typeof(ValidarDXController));
        BaseDatos bd = new BaseDatos();
        // GET: Home
        

        public ActionResult Index()
        {
            BaseDatos bd = new BaseDatos();
            this.recuperarDiagnosticos();
            log.Debug("INDEX INICIO");
            this.recupearReglasDiagnosticos();
            return View(this.recuperarDiagnosticos());
        }

        
        public List<Dx> recuperarDiagnosticos()
        {
            List<Dx> lisDiagnosticos = new List<Dx>();
            string connectionString = "Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=SEHTA;Data Source=DESKTOP-KV23RRC\\SQL_SERVER";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string query = "exec prc_obtener_dxs_nuevos";

                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Dx dx = new Dx()
                            {
                                id = reader.GetInt32(0),
                                edad = reader.GetInt32(1),
                                sistolica = reader.GetInt32(2),
                                diastolica = reader.GetInt32(3),
                                arp = reader.GetDouble(4),
                                conc_aldo = reader.GetDouble(5),
                                cromogranina_a = reader.GetDouble(6),
                                dopamina = reader.GetDouble(7),
                                epinefrina = reader.GetDouble(8),
                                igf1 = reader.GetDouble(9),
                                norepinefrina = reader.GetDouble(10),
                                serotonina = reader.GetDouble(11),
                                t4 = reader.GetDouble(12),
                                tsh = reader.GetDouble(13),
                                acido_5_hidrox = reader.GetDouble(14),
                                acido_vainillin_man = reader.GetDouble(15),
                                cortisol_libre = reader.GetDouble(16),
                                epinefrina_orina = reader.GetDouble(17),
                                norepinefrina_orina = reader.GetDouble(18),
                                proteinuria = reader.GetDouble(19),
                                sodio = reader.GetDouble(20),
                                supr_dexa = reader.GetDouble(21),
                                tfg = reader.GetDouble(22),
                                coartacion = reader.GetBoolean(23),
                                estenosis_renal = reader.GetBoolean(24),
                                quistes = reader.GetInt32(25),
                                iah = reader.GetInt32(26),
                                cortisol_nocturno = reader.GetDouble(27),
                                ant_poliquistosis = reader.GetBoolean(28),
                                cons_drogdas = reader.GetBoolean(29),
                                cons_otras = reader.GetBoolean(30),
                                cons_farmacos = reader.GetBoolean(31),
                                nivelPA = reader.GetString(32),
                                etiologia = reader.GetString(33),
                                estado = reader.GetString(34),
                                comentario = reader.GetString(35),
                            };

                            lisDiagnosticos.Add(dx);
                        }
                    }
                }
            }

            return lisDiagnosticos;
        }


        public int ValidarDX(string idDx , string comentario, string estado)
        {
            int op = 0;
            log.Debug("rechazar diagnostico funcion");
            string connectionString = "Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=SEHTA;Data Source=DESKTOP-KV23RRC\\SQL_SERVER";
           
            string updateQuery = "UPDATE diagnostico SET estado = @NuevoValor1, comentario = @NuevoValor2 WHERE id= " + idDx;

            try
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    using (SqlCommand command = new SqlCommand(updateQuery, connection))
                    {
                        // Parámetros para la consulta
                        command.Parameters.AddWithValue("@NuevoValor1", estado);
                        command.Parameters.AddWithValue("@NuevoValor2", comentario);
                        // Puedes agregar más parámetros según sea necesario

                        // Ejecutar la consulta de actualización
                        int rowsAffected = command.ExecuteNonQuery();

                        log.Debug($"Filas afectadas: {rowsAffected}");
                        op = rowsAffected;
                    }
                }
            }
            catch (Exception ex)
            {
                log.Debug("Error: " + ex.Message);
            }
            return op;
        }

        public void recupearReglasDiagnosticos()
        {
            List<Regla> lisreglas = new List<Regla>();
            string connectionString = "Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=SEHTA;Data Source=DESKTOP-KV23RRC\\SQL_SERVER";

            string updateQuery = "select * from dbo.reglas_diagnostico";

            try
            {
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    using (SqlCommand command = new SqlCommand(updateQuery, connection))
                    {
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                // Aquí, debes mapear los valores de las columnas a propiedades de tu clase
                                Regla r = new Regla()
                                {
                                    idDx = reader.GetInt32(1),
                                    regla = reader.GetString(2),
                                    
                                // Agrega más propiedades según tu tabla
                                };
                                log.Debug("Recuperado idDX:" + reader.GetInt32(1) + "rEGLA: " + reader.GetString(2));
                                lisreglas.Add(r);
                            }
                        }
                    }
                }
                //guardo el listado de reglas utilizadas para los diagnosticos
                System.Web.HttpContext.Current.Session["lisReglas"] = lisreglas;
            }
            catch (Exception ex)
            {
                log.Debug("Error: " + ex.Message);
            }
        }

        [HttpPost]
        public ActionResult obtenerReglas(string dx)
        {
            //recupero todas las reglas de todos los diagnosticos
            List<Regla> lisreglas = (List<Regla>)System.Web.HttpContext.Current.Session["lisReglas"];
            List<Regla> lr = new List<Regla>();

            if(lisreglas != null)
                foreach( Regla r in lisreglas)
                {
                        if (r.idDx == Int32.Parse(dx))
                            lr.Add(r);
                }
            log.Debug(Json(lr, JsonRequestBehavior.AllowGet));
            return Json(lr, JsonRequestBehavior.AllowGet);
        }
    } 
    
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<body id="body-pd">
    <header class="header" id="header">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>

        <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
    </header>
    <div class="l-navbar" id="nav-bar">
        <nav class="nav">
            <div>
                <a href="#" class="nav_logo"> <i class='bx bx-layer nav_logo-icon'></i> <span class="nav_logo-name">SEHTA</span> </a>
                <div class="nav_list">
                    <a href="@Url.Action("Index", "Home")" class="nav_link"><i class='bx bx-grid-alt nav_icon'></i> <span class="nav_name"> Realizar Diagnostico</span></a>
                    <a href="@Url.Action("Index", "ValidarDX")" class="nav_link" id="navBarButtonMail"><i class='bx bx-user nav_icon'></i> <span class="nav_name">Validar Diagnosticos</span></a>                    
                </div>
            </div>
        </nav>
    </div>
    <!--Container Main start-->

    <div class="height-100 bg-light">
        @RenderBody()
    </div>
    <!--Container Main end-->
</body>
</html>

<style>
    :root {
        --header-height: 3rem;
        --nav-width: 68px;
        --first-color: #000000;
        --first-color-light: #AFA5D9;
        --white-color: #F7F6FB;
        --body-font: 'Nunito', sans-serif;
        --normal-font-size: 1rem;
        --z-fixed: 100
    }

    *,
    ::before,
    ::after {
        box-sizing: border-box
    }

    body {
        position: relative;
        margin: var(--header-height) 0 0 0;
        padding: 0 1rem;
        font-family: var(--body-font);
        font-size: var(--normal-font-size);
        transition: .5s
    }

    a {
        text-decoration: none
    }

    .header {
        width: 100%;
        height: var(--header-height);
        position: fixed;
        top: 0;
        left: 0;
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 0 1rem;
        color: white;
        /* background-color: var(--white-color);*/
        background-color: #202020;
        z-index: var(--z-fixed);
        transition: .5s
    }

    .header_toggle {
        /*color: var(--first-color);*/
        color: #FFC799;
        font-size: 1.5rem;
        cursor: pointer
    }

    .header_img {
        width: 35px;
        height: 35px;
        display: flex;
        justify-content: center;
        border-radius: 50%;
        overflow: hidden
    }

        .header_img img {
            width: 40px
        }

    .l-navbar {
        position: fixed;
        top: 0;
        left: -30%;
        width: var(--nav-width);
        height: 100vh;
        background-color: var(--first-color);
        padding: .5rem 1rem 0 0;
        transition: .5s;
        z-index: var(--z-fixed)
    }

    .nav {
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        overflow: hidden
    }

    .nav_logo,
    .nav_link {
        display: grid;
        grid-template-columns: max-content max-content;
        align-items: center;
        column-gap: 1rem;
        padding: .5rem 0 .5rem 1.5rem
    }

    .nav_logo {
        margin-bottom: 2rem
    }

    .nav_logo-icon {
        font-size: 1.25rem;
        color: var(--white-color)
    }

    .nav_logo-name {
        color: var(--white-color);
        font-weight: 700
    }

    .nav_link {
        position: relative;
        /* color: var(--first-color-light);*/
        color: #FFC799;
        margin-bottom: 1.5rem;
        transition: .3s
    }

        .nav_link:hover {
            color: var(--white-color)
        }

    .nav_icon {
        font-size: 1.25rem
    }

    .show {
        left: 0
    }

    .body-pd {
        padding-left: calc(var(--nav-width) + 1rem)
    }

    .active {
        color: var(--white-color)
    }

        .active::before {
            content: '';
            position: absolute;
            left: 0;
            width: 2px;
            height: 32px;
            background-color: var(--white-color)
        }

    .height-100 {
        height: 100vh;
        width: 1900px;
    }

    .header {
        height: calc(var(--header-height) + 1rem);
        padding: 0 2rem 0 calc(var(--nav-width) + 2rem)
    }

    .header_img {
        width: 40px;
        height: 40px
    }

        .header_img img {
            width: 45px
        }

    .l-navbar {
        left: 0;
        padding: 1rem 1rem 0 0
    }

    .show {
        width: calc(var(--nav-width) + 156px)
    }

    .body-pd {
        padding-left: calc(var(--nav-width) + 188px)
    }
</style>

<script>
    document.addEventListener("DOMContentLoaded", function (event) {

        const showNavbar = (toggleId, navId, bodyId, headerId) => {
            const toggle = document.getElementById(toggleId),
                nav = document.getElementById(navId),
                bodypd = document.getElementById(bodyId),
                headerpd = document.getElementById(headerId)

            // Validate that all variables exist
            if (toggle && nav && bodypd && headerpd) {
                toggle.addEventListener('click', () => {
                    // show navbar
                    nav.classList.toggle('show')
                    // change icon
                    toggle.classList.toggle('bx-x')
                    // add padding to body
                    bodypd.classList.toggle('body-pd')
                    // add padding to header
                    headerpd.classList.toggle('body-pd')
                })
            }
        }

        showNavbar('header-toggle', 'nav-bar', 'body-pd', 'header')

        /*===== LINK ACTIVE =====*/
        const linkColor = document.querySelectorAll('.nav_link')

        function colorLink() {
            if (linkColor) {
                linkColor.forEach(l => l.classList.remove('active'))
                this.classList.add('active')
            }
        }
        linkColor.forEach(l => l.addEventListener('click', colorLink))

        // Your code to run since DOM is loaded and ready
    });
</script>